import NiceCertified.TwoThree.Base5

/-!
Generated by `gen/gen.py 6 2 3 20 --chunked 2500`; do not edit by hand.

Part 0 of 1: `[5, 9)`, about 2 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base6_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_0 : NiceFree 6 2 3 5 9 :=
  NiceFree.of_chain (by decide) [
    ⟨5, 6, 0, 2, 3, 0⟩,
    ⟨6, 9, 0, 3, 4, 0⟩] (by decide +kernel)

theorem upto_0 : NiceFree 6 2 3 (4 + 1) 9 := part_0

end Nice.Cert.Base6_2_3
