import NiceCertified.TwoThree.Base9

/-!
Generated by `gen/gen.py 11 2 3 20 --chunked 2500`; do not edit by hand.

Part 0 of 1: `[75, 196)`, about 2 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base11_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_0 : NiceFree 11 2 3 75 196 :=
  NiceFree.of_chain (by decide) [
    ⟨75, 121, 0, 4, 6, 0⟩,
    ⟨121, 196, 0, 5, 7, 0⟩] (by decide +kernel)

theorem upto_0 : NiceFree 11 2 3 (74 + 1) 196 := part_0

end Nice.Cert.Base11_2_3
