import NiceCertified.TwoThree.Base14

/-!
Generated by `gen/gen.py 15 2 3 20 --chunked 2500`; do not edit by hand.

Part 0 of 1: `[1143, 3375)`, about 2019 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base15_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_0 : NiceFree 15 2 3 1143 3375 :=
  NiceFree.of_chain (by decide) [
    ⟨1143, 1369, 0, 6, 8, 0⟩,
    ⟨1369, 3375, 3, 6, 9, 20⟩] (by decide +kernel)

theorem upto_0 : NiceFree 15 2 3 (1142 + 1) 3375 := part_0

end Nice.Cert.Base15_2_3
