import NiceCertified.TwoThree.Base3

/-!
Generated by `gen/gen.py 4 2 3 20 --chunked 2500`; do not edit by hand.

Part 0 of 1: `[2, 4)`, about 2 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base4_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_0 : NiceFree 4 2 3 2 4 :=
  NiceFree.of_chain (by decide) [
    ⟨2, 3, 3, 2, 2, 20⟩,
    ⟨3, 4, 0, 2, 3, 0⟩] (by decide +kernel)

theorem upto_0 : NiceFree 4 2 3 (1 + 1) 4 := part_0

end Nice.Cert.Base4_2_3
