import NiceCertified.TwoThree.Base16

/-!
Generated by `gen/gen.py 17 2 3 20 --chunked 2500`; do not edit by hand.

Part 0 of 3: `[4913, 8670)`, about 2319 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base17_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_0 : NiceFree 17 2 3 4913 8670 :=
  NiceFree.of_chain (by decide) [
    ⟨4913, 5202, 3, 7, 10, 20⟩,
    ⟨5202, 5491, 3, 7, 10, 20⟩,
    ⟨5491, 5780, 3, 7, 10, 20⟩,
    ⟨5780, 6069, 3, 7, 10, 20⟩,
    ⟨6069, 6358, 3, 7, 10, 20⟩,
    ⟨6358, 6647, 3, 7, 10, 20⟩,
    ⟨6647, 6936, 3, 7, 10, 20⟩,
    ⟨6936, 7225, 3, 7, 10, 20⟩,
    ⟨7225, 7514, 3, 7, 10, 20⟩,
    ⟨7514, 7803, 3, 7, 10, 20⟩,
    ⟨7803, 8092, 3, 7, 10, 20⟩,
    ⟨8092, 8381, 3, 7, 10, 20⟩,
    ⟨8381, 8670, 3, 7, 10, 20⟩] (by decide +kernel)

theorem upto_0 : NiceFree 17 2 3 (4912 + 1) 8670 := part_0

end Nice.Cert.Base17_2_3
