import NiceCertified.TwoThree.Base17.Part000

/-!
Generated by `gen/gen.py 17 2 3 20 --chunked 2500`; do not edit by hand.

Part 1 of 3: `[8670, 10982)`, about 2292 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base17_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_1 : NiceFree 17 2 3 8670 10982 :=
  NiceFree.of_chain (by decide) [
    ⟨8670, 8959, 3, 7, 10, 20⟩,
    ⟨8959, 9248, 3, 7, 10, 20⟩,
    ⟨9248, 9537, 3, 7, 10, 20⟩,
    ⟨9537, 9826, 3, 7, 10, 20⟩,
    ⟨9826, 10115, 3, 7, 10, 20⟩,
    ⟨10115, 10404, 3, 7, 10, 20⟩,
    ⟨10404, 10693, 3, 7, 10, 20⟩,
    ⟨10693, 10982, 3, 7, 10, 20⟩] (by decide +kernel)

theorem upto_1 : NiceFree 17 2 3 (4912 + 1) 10982 :=
  upto_0.trans part_1

end Nice.Cert.Base17_2_3
