import NiceCertified.TwoThree.Base17.Part001

/-!
Generated by `gen/gen.py 17 2 3 20 --chunked 2500`; do not edit by hand.

Part 2 of 3: `[10982, 15260)`, about 1750 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base17_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_2 : NiceFree 17 2 3 10982 15260 :=
  NiceFree.of_chain (by decide) [
    ⟨10982, 11271, 3, 7, 10, 20⟩,
    ⟨11271, 11560, 3, 7, 10, 20⟩,
    ⟨11560, 11849, 3, 7, 10, 20⟩,
    ⟨11849, 12138, 3, 7, 10, 20⟩,
    ⟨12138, 12427, 3, 7, 10, 20⟩,
    ⟨12427, 12633, 3, 7, 10, 20⟩,
    ⟨12633, 15260, 0, 7, 11, 0⟩] (by decide +kernel)

theorem upto_2 : NiceFree 17 2 3 (4912 + 1) 15260 :=
  upto_1.trans part_2

end Nice.Cert.Base17_2_3
