import NiceCertified.TwoThree.Base4

/-!
Generated by `gen/gen.py 5 2 3 20 --chunked 2500`; do not edit by hand.

Part 0 of 1: `[3, 5)`, about 3 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base5_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_0 : NiceFree 5 2 3 3 5 :=
  NiceFree.of_chain (by decide) [
    ⟨3, 5, 3, 2, 3, 20⟩] (by decide +kernel)

theorem upto_0 : NiceFree 5 2 3 (2 + 1) 5 := part_0

end Nice.Cert.Base5_2_3
