import NiceCertified.TwoThree.Base8

/-!
Generated by `gen/gen.py 9 2 3 20 --chunked 2500`; do not edit by hand.

Part 0 of 1: `[22, 53)`, about 15 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base9_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_0 : NiceFree 9 2 3 22 53 :=
  NiceFree.of_chain (by decide) [
    ⟨22, 27, 0, 3, 5, 0⟩,
    ⟨27, 39, 3, 4, 5, 20⟩,
    ⟨39, 53, 0, 4, 6, 0⟩] (by decide +kernel)

theorem upto_0 : NiceFree 9 2 3 (21 + 1) 53 := part_0

end Nice.Cert.Base9_2_3
