import NiceCertified.TwoThree.Base15

/-!
Generated by `gen/gen.py 16 2 3 20 --chunked 2500`; do not edit by hand.

Part 0 of 1: `[2353, 7132)`, about 2 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base16_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_0 : NiceFree 16 2 3 2353 7132 :=
  NiceFree.of_chain (by decide) [
    ⟨2353, 4096, 0, 6, 9, 0⟩,
    ⟨4096, 7132, 0, 7, 10, 0⟩] (by decide +kernel)

theorem upto_0 : NiceFree 16 2 3 (2352 + 1) 7132 := part_0

end Nice.Cert.Base16_2_3
