import NiceCertified.TwoThree.Base18.Part000

/-!
Generated by `gen/gen.py 18 2 3 20 --chunked 2500`; do not edit by hand.

Part 1 of 4: `[18468, 21060)`, about 2442 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base18_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_1 : NiceFree 18 2 3 18468 21060 :=
  NiceFree.of_chain (by decide) [
    ⟨18468, 18792, 3, 7, 11, 20⟩,
    ⟨18792, 19116, 3, 7, 11, 20⟩,
    ⟨19116, 19440, 3, 7, 11, 20⟩,
    ⟨19440, 19764, 3, 7, 11, 20⟩,
    ⟨19764, 20088, 3, 7, 11, 20⟩,
    ⟨20088, 20412, 3, 7, 11, 20⟩,
    ⟨20412, 20736, 3, 7, 11, 20⟩,
    ⟨20736, 21060, 3, 7, 11, 20⟩] (by decide +kernel)

theorem upto_1 : NiceFree 18 2 3 (10396 + 1) 21060 :=
  upto_0.trans part_1

end Nice.Cert.Base18_2_3
