import NiceCertified.TwoThree.Base18.Part001

/-!
Generated by `gen/gen.py 18 2 3 20 --chunked 2500`; do not edit by hand.

Part 2 of 4: `[21060, 23328)`, about 2112 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base18_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_2 : NiceFree 18 2 3 21060 23328 :=
  NiceFree.of_chain (by decide) [
    ⟨21060, 21384, 3, 7, 11, 20⟩,
    ⟨21384, 21708, 3, 7, 11, 20⟩,
    ⟨21708, 22032, 3, 7, 11, 20⟩,
    ⟨22032, 22356, 3, 7, 11, 20⟩,
    ⟨22356, 22680, 3, 7, 11, 20⟩,
    ⟨22680, 23004, 3, 7, 11, 20⟩,
    ⟨23004, 23328, 3, 7, 11, 20⟩] (by decide +kernel)

theorem upto_2 : NiceFree 18 2 3 (10396 + 1) 23328 :=
  upto_1.trans part_2

end Nice.Cert.Base18_2_3
