import NiceCertified.TwoThree.Base18.Part002

/-!
Generated by `gen/gen.py 18 2 3 20 --chunked 2500`; do not edit by hand.

Part 3 of 4: `[23328, 33036)`, about 1368 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base18_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_3 : NiceFree 18 2 3 23328 33036 :=
  NiceFree.of_chain (by decide) [
    ⟨23328, 24744, 3, 7, 11, 20⟩,
    ⟨24744, 33036, 0, 8, 11, 0⟩] (by decide +kernel)

theorem upto_3 : NiceFree 18 2 3 (10396 + 1) 33036 :=
  upto_2.trans part_3

end Nice.Cert.Base18_2_3
