import NiceCertified.TwoThree.Base17

/-!
Generated by `gen/gen.py 18 2 3 20 --chunked 2500`; do not edit by hand.

Part 0 of 4: `[10397, 18468)`, about 2455 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base18_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_0 : NiceFree 18 2 3 10397 18468 :=
  NiceFree.of_chain (by decide) [
    ⟨10397, 15285, 0, 7, 10, 0⟩,
    ⟨15285, 17496, 3, 7, 11, 20⟩,
    ⟨17496, 17820, 3, 7, 11, 20⟩,
    ⟨17820, 18144, 3, 7, 11, 20⟩,
    ⟨18144, 18468, 3, 7, 11, 20⟩] (by decide +kernel)

theorem upto_0 : NiceFree 18 2 3 (10396 + 1) 18468 := part_0

end Nice.Cert.Base18_2_3
