import NiceCertified.TwoThree.Base11

/-!
Generated by `gen/gen.py 12 2 3 20 --chunked 2500`; do not edit by hand.

Part 0 of 1: `[144, 390)`, about 172 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base12_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_0 : NiceFree 12 2 3 144 390 :=
  NiceFree.of_chain (by decide) [
    ⟨144, 330, 3, 5, 7, 20⟩,
    ⟨330, 390, 0, 5, 8, 0⟩] (by decide +kernel)

theorem upto_0 : NiceFree 12 2 3 (143 + 1) 390 := part_0

end Nice.Cert.Base12_2_3
