import NiceCertified.TwoThree.Base12

/-!
Generated by `gen/gen.py 13 2 3 20 --chunked 2500`; do not edit by hand.

Part 0 of 1: `[283, 788)`, about 236 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base13_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_0 : NiceFree 13 2 3 283 788 :=
  NiceFree.of_chain (by decide) [
    ⟨283, 398, 0, 5, 7, 0⟩,
    ⟨398, 610, 3, 5, 8, 20⟩,
    ⟨610, 788, 0, 6, 8, 0⟩] (by decide +kernel)

theorem upto_0 : NiceFree 13 2 3 (282 + 1) 788 := part_0

end Nice.Cert.Base13_2_3
