import NiceCertified.TwoThree.Base6

/-!
Generated by `gen/gen.py 7 2 3 20 --chunked 2500`; do not edit by hand.

Part 0 of 1: `[7, 16)`, about 9 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base7_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_0 : NiceFree 7 2 3 7 16 :=
  NiceFree.of_chain (by decide) [
    ⟨7, 14, 3, 3, 4, 20⟩,
    ⟨14, 16, 0, 3, 5, 0⟩] (by decide +kernel)

theorem upto_0 : NiceFree 7 2 3 (6 + 1) 16 := part_0

end Nice.Cert.Base7_2_3
