import NiceCertified.TwoThree.Base16.Part000

/-!
Generated by `gen/gen.py 16 2 3 20 --chunked 2500`; do not edit by hand.

The crude band `(2352, 7132)` in 1 parts, about 2 tree nodes and scanned
candidates in all, checked by the kernel's own tree search with scan width 20.
-/

namespace Nice.Cert

/-- **No `(2,3)`-nice number exists in base 16.** -/
theorem base_16_empty_2_3 (n : Nat) : ¬ Pandigital 16 2 3 n :=
  no_nice_of_free (lo := 2352) (hi := 7132) (by decide) (by decide) (by decide)
    Nice.Cert.Base16_2_3.upto_0 n

end Nice.Cert
