import NiceCertified.TwoThree.Base9.Part000

/-!
Generated by `gen/gen.py 9 2 3 20 --chunked 2500`; do not edit by hand.

The crude band `(21, 53)` in 1 parts, about 15 tree nodes and scanned
candidates in all, checked by the kernel's own tree search with scan width 20.
-/

namespace Nice.Cert

/-- **No `(2,3)`-nice number exists in base 9.** -/
theorem base_9_empty_2_3 (n : Nat) : ¬ Pandigital 9 2 3 n :=
  no_nice_of_free (lo := 21) (hi := 53) (by decide) (by decide) (by decide)
    Nice.Cert.Base9_2_3.upto_0 n

end Nice.Cert
