import NiceCertified.TwoThree.Base5.Part000

/-!
Generated by `gen/gen.py 5 2 3 20 --chunked 2500`; do not edit by hand.

The crude band `(2, 5)` in 1 parts, about 3 tree nodes and scanned
candidates in all, checked by the kernel's own tree search with scan width 20.
-/

namespace Nice.Cert

/-- **No `(2,3)`-nice number exists in base 5.** -/
theorem base_5_empty_2_3 (n : Nat) : ¬ Pandigital 5 2 3 n :=
  no_nice_of_free (lo := 2) (hi := 5) (by decide) (by decide) (by decide)
    Nice.Cert.Base5_2_3.upto_0 n

end Nice.Cert
