import NiceCertified.Checker

/-!
Generated by `gen/gen.py 9 2 3 9`; do not edit by hand.

4 intervals covering `(21, 53)`: 2 with the wrong digit lengths,
0 retired by a top-digit clash, 2 scanned candidate by candidate
(12 candidates).
-/

namespace Nice.Cert

def cert_9_2_3 : List Ent := [
  ⟨22, 27, 0, 3, 5, 0⟩,
  ⟨27, 36, 2, 4, 5, 0⟩,
  ⟨36, 39, 2, 4, 5, 0⟩,
  ⟨39, 53, 0, 4, 6, 0⟩]

set_option maxRecDepth 100000 in
theorem cert_9_2_3_ok : checkChain 9 2 3 (21 + 1) cert_9_2_3 53 = true := by
  decide +kernel

/-- **No `(2,3)`-nice number exists in base 9.** -/
theorem base_9_empty_2_3 (n : Nat) : ¬ Pandigital 9 2 3 n :=
  no_nice_of_cert (lo := 21) (hi := 53) (by decide) (by decide) (by decide)
    cert_9_2_3 cert_9_2_3_ok n

end Nice.Cert
