import NiceCertified.TwoThree.Base13.Part000

/-!
Generated by `gen/gen.py 13 2 3 20 --chunked 2500`; do not edit by hand.

The crude band `(282, 788)` in 1 parts, about 236 tree nodes and scanned
candidates in all, checked by the kernel's own tree search with scan width 20.
-/

namespace Nice.Cert

/-- **No `(2,3)`-nice number exists in base 13.** -/
theorem base_13_empty_2_3 (n : Nat) : ¬ Pandigital 13 2 3 n :=
  no_nice_of_free (lo := 282) (hi := 788) (by decide) (by decide) (by decide)
    Nice.Cert.Base13_2_3.upto_0 n

end Nice.Cert
