import NiceCertified.TwoThree.Base4.Part000

/-!
Generated by `gen/gen.py 4 2 3 20 --chunked 2500`; do not edit by hand.

The crude band `(1, 4)` in 1 parts, about 2 tree nodes and scanned
candidates in all, checked by the kernel's own tree search with scan width 20.
-/

namespace Nice.Cert

/-- **No `(2,3)`-nice number exists in base 4.** -/
theorem base_4_empty_2_3 (n : Nat) : ¬ Pandigital 4 2 3 n :=
  no_nice_of_free (lo := 1) (hi := 4) (by decide) (by decide) (by decide)
    Nice.Cert.Base4_2_3.upto_0 n

end Nice.Cert
