import NiceCertified.TwoThree.Base7.Part000

/-!
Generated by `gen/gen.py 7 2 3 20 --chunked 2500`; do not edit by hand.

The crude band `(6, 16)` in 1 parts, about 9 tree nodes and scanned
candidates in all, checked by the kernel's own tree search with scan width 20.
-/

namespace Nice.Cert

/-- **No `(2,3)`-nice number exists in base 7.** -/
theorem base_7_empty_2_3 (n : Nat) : ¬ Pandigital 7 2 3 n :=
  no_nice_of_free (lo := 6) (hi := 16) (by decide) (by decide) (by decide)
    Nice.Cert.Base7_2_3.upto_0 n

end Nice.Cert
