import NiceCertified.Checker

/-!
Generated by `gen/gen.py 7 2 3 7`; do not edit by hand.

2 intervals covering `(6, 16)`: 1 with the wrong digit lengths,
0 retired by a top-digit clash, 1 scanned candidate by candidate
(7 candidates).
-/

namespace Nice.Cert

def cert_7_2_3 : List Ent := [
  ⟨7, 14, 2, 3, 4, 0⟩,
  ⟨14, 16, 0, 3, 5, 0⟩]

set_option maxRecDepth 100000 in
theorem cert_7_2_3_ok : checkChain 7 2 3 (6 + 1) cert_7_2_3 16 = true := by
  decide +kernel

/-- **No `(2,3)`-nice number exists in base 7.** -/
theorem base_7_empty_2_3 (n : Nat) : ¬ Pandigital 7 2 3 n :=
  no_nice_of_cert (lo := 6) (hi := 16) (by decide) (by decide) (by decide)
    cert_7_2_3 cert_7_2_3_ok n

end Nice.Cert
