import NiceCertified.TwoThree.Base18.Part003

/-!
Generated by `gen/gen.py 18 2 3 20 --chunked 2500`; do not edit by hand.

The crude band `(10396, 33036)` in 4 parts, about 8377 tree nodes and scanned
candidates in all, checked by the kernel's own tree search with scan width 20.
-/

namespace Nice.Cert

/-- **No `(2,3)`-nice number exists in base 18.** -/
theorem base_18_empty_2_3 (n : Nat) : ¬ Pandigital 18 2 3 n :=
  no_nice_of_free (lo := 10396) (hi := 33036) (by decide) (by decide) (by decide)
    Nice.Cert.Base18_2_3.upto_3 n

end Nice.Cert
