import NiceCertified.Checker

/-!
Generated by `gen/gen.py 3 2 3 3`; do not edit by hand.

0 intervals covering `(1, 2)`: 0 with the wrong digit lengths,
0 retired by a top-digit clash, 0 scanned candidate by candidate
(0 candidates).
-/

namespace Nice.Cert

def cert_3_2_3 : List Ent := [
  ]

set_option maxRecDepth 100000 in
theorem cert_3_2_3_ok : checkChain 3 2 3 (1 + 1) cert_3_2_3 2 = true := by
  decide +kernel

/-- **No `(2,3)`-nice number exists in base 3.** -/
theorem base_3_empty_2_3 (n : Nat) : ¬ Pandigital 3 2 3 n :=
  no_nice_of_cert (lo := 1) (hi := 2) (by decide) (by decide) (by decide)
    cert_3_2_3 cert_3_2_3_ok n

end Nice.Cert
