import NiceCertified.Checker

/-!
Generated by `gen/gen.py 4 2 3 4`; do not edit by hand.

2 intervals covering `(1, 4)`: 1 with the wrong digit lengths,
1 retired by a top-digit clash, 0 scanned candidate by candidate
(0 candidates).
-/

namespace Nice.Cert

def cert_4_2_3 : List Ent := [
  ⟨2, 3, 1, 2, 2, 2⟩,
  ⟨3, 4, 0, 2, 3, 0⟩]

set_option maxRecDepth 100000 in
theorem cert_4_2_3_ok : checkChain 4 2 3 (1 + 1) cert_4_2_3 4 = true := by
  decide +kernel

/-- **No `(2,3)`-nice number exists in base 4.** -/
theorem base_4_empty_2_3 (n : Nat) : ¬ Pandigital 4 2 3 n :=
  no_nice_of_cert (lo := 1) (hi := 4) (by decide) (by decide) (by decide)
    cert_4_2_3 cert_4_2_3_ok n

end Nice.Cert
