import NiceCertified.Checker

/-!
Generated by `gen/gen.py 14 2 3 14`; do not edit by hand.

32 intervals covering `(563, 1619)`: 2 with the wrong digit lengths,
0 retired by a top-digit clash, 30 scanned candidate by candidate
(405 candidates).
-/

namespace Nice.Cert

def cert_14_2_3 : List Ent := [
  ⟨564, 734, 0, 5, 8, 0⟩,
  ⟨734, 742, 2, 6, 8, 0⟩,
  ⟨742, 756, 2, 6, 8, 0⟩,
  ⟨756, 770, 2, 6, 8, 0⟩,
  ⟨770, 784, 2, 6, 8, 0⟩,
  ⟨784, 798, 2, 6, 8, 0⟩,
  ⟨798, 812, 2, 6, 8, 0⟩,
  ⟨812, 826, 2, 6, 8, 0⟩,
  ⟨826, 840, 2, 6, 8, 0⟩,
  ⟨840, 854, 2, 6, 8, 0⟩,
  ⟨854, 868, 2, 6, 8, 0⟩,
  ⟨868, 882, 2, 6, 8, 0⟩,
  ⟨882, 896, 2, 6, 8, 0⟩,
  ⟨896, 910, 2, 6, 8, 0⟩,
  ⟨910, 924, 2, 6, 8, 0⟩,
  ⟨924, 938, 2, 6, 8, 0⟩,
  ⟨938, 952, 2, 6, 8, 0⟩,
  ⟨952, 966, 2, 6, 8, 0⟩,
  ⟨966, 980, 2, 6, 8, 0⟩,
  ⟨980, 994, 2, 6, 8, 0⟩,
  ⟨994, 1008, 2, 6, 8, 0⟩,
  ⟨1008, 1022, 2, 6, 8, 0⟩,
  ⟨1022, 1036, 2, 6, 8, 0⟩,
  ⟨1036, 1050, 2, 6, 8, 0⟩,
  ⟨1050, 1064, 2, 6, 8, 0⟩,
  ⟨1064, 1078, 2, 6, 8, 0⟩,
  ⟨1078, 1092, 2, 6, 8, 0⟩,
  ⟨1092, 1106, 2, 6, 8, 0⟩,
  ⟨1106, 1120, 2, 6, 8, 0⟩,
  ⟨1120, 1134, 2, 6, 8, 0⟩,
  ⟨1134, 1139, 2, 6, 8, 0⟩,
  ⟨1139, 1619, 0, 6, 9, 0⟩]

set_option maxRecDepth 100000 in
theorem cert_14_2_3_ok : checkChain 14 2 3 (563 + 1) cert_14_2_3 1619 = true := by
  decide +kernel

/-- **No `(2,3)`-nice number exists in base 14.** -/
theorem base_14_empty_2_3 (n : Nat) : ¬ Pandigital 14 2 3 n :=
  no_nice_of_cert (lo := 563) (hi := 1619) (by decide) (by decide) (by decide)
    cert_14_2_3 cert_14_2_3_ok n

end Nice.Cert
