import NiceCertified.Checker

/-!
Generated by `gen/gen.py 5 2 3 5`; do not edit by hand.

1 intervals covering `(2, 5)`: 0 with the wrong digit lengths,
0 retired by a top-digit clash, 1 scanned candidate by candidate
(2 candidates).
-/

namespace Nice.Cert

def cert_5_2_3 : List Ent := [
  ⟨3, 5, 2, 2, 3, 0⟩]

set_option maxRecDepth 100000 in
theorem cert_5_2_3_ok : checkChain 5 2 3 (2 + 1) cert_5_2_3 5 = true := by
  decide +kernel

/-- **No `(2,3)`-nice number exists in base 5.** -/
theorem base_5_empty_2_3 (n : Nat) : ¬ Pandigital 5 2 3 n :=
  no_nice_of_cert (lo := 2) (hi := 5) (by decide) (by decide) (by decide)
    cert_5_2_3 cert_5_2_3_ok n

end Nice.Cert
