import NiceCertified.Checker

/-!
Generated by `gen/gen.py 12 2 3 12`; do not edit by hand.

17 intervals covering `(143, 390)`: 1 with the wrong digit lengths,
3 retired by a top-digit clash, 13 scanned candidate by candidate
(150 candidates).
-/

namespace Nice.Cert

def cert_12_2_3 : List Ent := [
  ⟨144, 156, 1, 5, 7, 1⟩,
  ⟨156, 168, 1, 5, 7, 1⟩,
  ⟨168, 180, 1, 5, 7, 1⟩,
  ⟨180, 192, 2, 5, 7, 0⟩,
  ⟨192, 204, 2, 5, 7, 0⟩,
  ⟨204, 216, 2, 5, 7, 0⟩,
  ⟨216, 228, 2, 5, 7, 0⟩,
  ⟨228, 240, 2, 5, 7, 0⟩,
  ⟨240, 252, 2, 5, 7, 0⟩,
  ⟨252, 264, 2, 5, 7, 0⟩,
  ⟨264, 276, 2, 5, 7, 0⟩,
  ⟨276, 288, 2, 5, 7, 0⟩,
  ⟨288, 300, 2, 5, 7, 0⟩,
  ⟨300, 312, 2, 5, 7, 0⟩,
  ⟨312, 324, 2, 5, 7, 0⟩,
  ⟨324, 330, 2, 5, 7, 0⟩,
  ⟨330, 390, 0, 5, 8, 0⟩]

set_option maxRecDepth 100000 in
theorem cert_12_2_3_ok : checkChain 12 2 3 (143 + 1) cert_12_2_3 390 = true := by
  decide +kernel

/-- **No `(2,3)`-nice number exists in base 12.** -/
theorem base_12_empty_2_3 (n : Nat) : ¬ Pandigital 12 2 3 n :=
  no_nice_of_cert (lo := 143) (hi := 390) (by decide) (by decide) (by decide)
    cert_12_2_3 cert_12_2_3_ok n

end Nice.Cert
