import NiceCertified.Checker

/-!
Generated by `gen/gen.py 6 2 3 6`; do not edit by hand.

2 intervals covering `(4, 9)`: 2 with the wrong digit lengths,
0 retired by a top-digit clash, 0 scanned candidate by candidate
(0 candidates).
-/

namespace Nice.Cert

def cert_6_2_3 : List Ent := [
  ⟨5, 6, 0, 2, 3, 0⟩,
  ⟨6, 9, 0, 3, 4, 0⟩]

set_option maxRecDepth 100000 in
theorem cert_6_2_3_ok : checkChain 6 2 3 (4 + 1) cert_6_2_3 9 = true := by
  decide +kernel

/-- **No `(2,3)`-nice number exists in base 6.** -/
theorem base_6_empty_2_3 (n : Nat) : ¬ Pandigital 6 2 3 n :=
  no_nice_of_cert (lo := 4) (hi := 9) (by decide) (by decide) (by decide)
    cert_6_2_3 cert_6_2_3_ok n

end Nice.Cert
