import NiceCertified.TwoThree.Base8.Part000

/-!
Generated by `gen/gen.py 8 2 3 20 --chunked 2500`; do not edit by hand.

The crude band `(12, 28)` in 1 parts, about 10 tree nodes and scanned
candidates in all, checked by the kernel's own tree search with scan width 20.
-/

namespace Nice.Cert

/-- **No `(2,3)`-nice number exists in base 8.** -/
theorem base_8_empty_2_3 (n : Nat) : ¬ Pandigital 8 2 3 n :=
  no_nice_of_free (lo := 12) (hi := 28) (by decide) (by decide) (by decide)
    Nice.Cert.Base8_2_3.upto_0 n

end Nice.Cert
