import NiceCertified.Checker

/-!
Generated by `gen/gen.py 16 2 3 16`; do not edit by hand.

2 intervals covering `(2352, 7132)`: 2 with the wrong digit lengths,
0 retired by a top-digit clash, 0 scanned candidate by candidate
(0 candidates).
-/

namespace Nice.Cert

def cert_16_2_3 : List Ent := [
  ⟨2353, 4096, 0, 6, 9, 0⟩,
  ⟨4096, 7132, 0, 7, 10, 0⟩]

set_option maxRecDepth 100000 in
theorem cert_16_2_3_ok : checkChain 16 2 3 (2352 + 1) cert_16_2_3 7132 = true := by
  decide +kernel

/-- **No `(2,3)`-nice number exists in base 16.** -/
theorem base_16_empty_2_3 (n : Nat) : ¬ Pandigital 16 2 3 n :=
  no_nice_of_cert (lo := 2352) (hi := 7132) (by decide) (by decide) (by decide)
    cert_16_2_3 cert_16_2_3_ok n

end Nice.Cert
