import NiceCertified.Checker

/-!
Generated by `gen/gen.py 11 2 3 11`; do not edit by hand.

2 intervals covering `(74, 196)`: 2 with the wrong digit lengths,
0 retired by a top-digit clash, 0 scanned candidate by candidate
(0 candidates).
-/

namespace Nice.Cert

def cert_11_2_3 : List Ent := [
  ⟨75, 121, 0, 4, 6, 0⟩,
  ⟨121, 196, 0, 5, 7, 0⟩]

set_option maxRecDepth 100000 in
theorem cert_11_2_3_ok : checkChain 11 2 3 (74 + 1) cert_11_2_3 196 = true := by
  decide +kernel

/-- **No `(2,3)`-nice number exists in base 11.** -/
theorem base_11_empty_2_3 (n : Nat) : ¬ Pandigital 11 2 3 n :=
  no_nice_of_cert (lo := 74) (hi := 196) (by decide) (by decide) (by decide)
    cert_11_2_3 cert_11_2_3_ok n

end Nice.Cert
