import NiceCertified.Checker

/-!
Generated by `gen/gen.py 2 2 3 2`; do not edit by hand.

1 intervals covering `(0, 2)`: 0 with the wrong digit lengths,
1 retired by a top-digit clash, 0 scanned candidate by candidate
(0 candidates).
-/

namespace Nice.Cert

def cert_2_2_3 : List Ent := [
  ⟨1, 2, 1, 1, 1, 1⟩]

set_option maxRecDepth 100000 in
theorem cert_2_2_3_ok : checkChain 2 2 3 (0 + 1) cert_2_2_3 2 = true := by
  decide +kernel

/-- **No `(2,3)`-nice number exists in base 2.** -/
theorem base_2_empty_2_3 (n : Nat) : ¬ Pandigital 2 2 3 n :=
  no_nice_of_cert (lo := 0) (hi := 2) (by decide) (by decide) (by decide)
    cert_2_2_3 cert_2_2_3_ok n

end Nice.Cert
