import NiceCertified.TwoThree.Base19.Part006

/-!
Generated by `gen/gen.py 19 2 3 20 --chunked 2500`; do not edit by hand.

The crude band `(22272, 72321)` in 7 parts, about 16346 tree nodes and scanned
candidates in all, checked by the kernel's own tree search with scan width 20.
-/

namespace Nice.Cert

/-- **No `(2,3)`-nice number exists in base 19.** -/
theorem base_19_empty_2_3 (n : Nat) : ¬ Pandigital 19 2 3 n :=
  no_nice_of_free (lo := 22272) (hi := 72321) (by decide) (by decide) (by decide)
    Nice.Cert.Base19_2_3.upto_6 n

end Nice.Cert
