import NiceCertified.TwoThree.Base15.Part000

/-!
Generated by `gen/gen.py 15 2 3 20 --chunked 2500`; do not edit by hand.

The crude band `(1142, 3375)` in 1 parts, about 2019 tree nodes and scanned
candidates in all, checked by the kernel's own tree search with scan width 20.
-/

namespace Nice.Cert

/-- **No `(2,3)`-nice number exists in base 15.** -/
theorem base_15_empty_2_3 (n : Nat) : ¬ Pandigital 15 2 3 n :=
  no_nice_of_free (lo := 1142) (hi := 3375) (by decide) (by decide) (by decide)
    Nice.Cert.Base15_2_3.upto_0 n

end Nice.Cert
