import NiceCertified.TwoThree.Base2

/-!
Generated by `gen/gen.py 3 2 3 20 --chunked 2500`; do not edit by hand.

The crude band `(1, 2)` in 0 parts, about 0 tree nodes and scanned
candidates in all, checked by the kernel's own tree search with scan width 20.
-/

namespace Nice.Cert

/-- **No `(2,3)`-nice number exists in base 3.** -/
theorem base_3_empty_2_3 (n : Nat) : ¬ Pandigital 3 2 3 n :=
  no_nice_of_free (lo := 1) (hi := 2) (by decide) (by decide) (by decide)
    (fun n h1 h2 => absurd (Nat.lt_of_le_of_lt h1 h2) (by decide)) n

end Nice.Cert
