import NiceCertified.TwoThree.Base20.Part035

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

The crude band `(48273, 160000)` in 36 parts, about 82274 tree nodes and scanned
candidates in all, checked by the kernel's own tree search with scan width 20.
-/

namespace Nice.Cert

/-- **No `(2,3)`-nice number exists in base 20.** -/
theorem base_20_empty_2_3 (n : Nat) : ¬ Pandigital 20 2 3 n :=
  no_nice_of_free (lo := 48273) (hi := 160000) (by decide) (by decide) (by decide)
    Nice.Cert.Base20_2_3.upto_35 n

end Nice.Cert
