import NiceCertified.TwoThree.Base14.Part000

/-!
Generated by `gen/gen.py 14 2 3 20 --chunked 2500`; do not edit by hand.

The crude band `(563, 1619)` in 1 parts, about 444 tree nodes and scanned
candidates in all, checked by the kernel's own tree search with scan width 20.
-/

namespace Nice.Cert

/-- **No `(2,3)`-nice number exists in base 14.** -/
theorem base_14_empty_2_3 (n : Nat) : ¬ Pandigital 14 2 3 n :=
  no_nice_of_free (lo := 563) (hi := 1619) (by decide) (by decide) (by decide)
    Nice.Cert.Base14_2_3.upto_0 n

end Nice.Cert
