import NiceCertified.TwoThree.Base12.Part000

/-!
Generated by `gen/gen.py 12 2 3 20 --chunked 2500`; do not edit by hand.

The crude band `(143, 390)` in 1 parts, about 172 tree nodes and scanned
candidates in all, checked by the kernel's own tree search with scan width 20.
-/

namespace Nice.Cert

/-- **No `(2,3)`-nice number exists in base 12.** -/
theorem base_12_empty_2_3 (n : Nat) : ¬ Pandigital 12 2 3 n :=
  no_nice_of_free (lo := 143) (hi := 390) (by decide) (by decide) (by decide)
    Nice.Cert.Base12_2_3.upto_0 n

end Nice.Cert
