import NiceCertified.Checker

/-!
Generated by `gen/gen.py 8 2 3 8`; do not edit by hand.

3 intervals covering `(12, 28)`: 2 with the wrong digit lengths,
0 retired by a top-digit clash, 1 scanned candidate by candidate
(7 candidates).
-/

namespace Nice.Cert

def cert_8_2_3 : List Ent := [
  ⟨13, 16, 0, 3, 4, 0⟩,
  ⟨16, 23, 2, 3, 5, 0⟩,
  ⟨23, 28, 0, 4, 5, 0⟩]

set_option maxRecDepth 100000 in
theorem cert_8_2_3_ok : checkChain 8 2 3 (12 + 1) cert_8_2_3 28 = true := by
  decide +kernel

/-- **No `(2,3)`-nice number exists in base 8.** -/
theorem base_8_empty_2_3 (n : Nat) : ¬ Pandigital 8 2 3 n :=
  no_nice_of_cert (lo := 12) (hi := 28) (by decide) (by decide) (by decide)
    cert_8_2_3 cert_8_2_3_ok n

end Nice.Cert
