import NiceCertified.TwoThree.Base2.Part000

/-!
Generated by `gen/gen.py 2 2 3 20 --chunked 2500`; do not edit by hand.

The crude band `(0, 2)` in 1 parts, about 1 tree nodes and scanned
candidates in all, checked by the kernel's own tree search with scan width 20.
-/

namespace Nice.Cert

/-- **No `(2,3)`-nice number exists in base 2.** -/
theorem base_2_empty_2_3 (n : Nat) : ¬ Pandigital 2 2 3 n :=
  no_nice_of_free (lo := 0) (hi := 2) (by decide) (by decide) (by decide)
    Nice.Cert.Base2_2_3.upto_0 n

end Nice.Cert
