import NiceCertified.TwoThree.Base17.Part002

/-!
Generated by `gen/gen.py 17 2 3 20 --chunked 2500`; do not edit by hand.

The crude band `(4912, 15260)` in 3 parts, about 6361 tree nodes and scanned
candidates in all, checked by the kernel's own tree search with scan width 20.
-/

namespace Nice.Cert

/-- **No `(2,3)`-nice number exists in base 17.** -/
theorem base_17_empty_2_3 (n : Nat) : ¬ Pandigital 17 2 3 n :=
  no_nice_of_free (lo := 4912) (hi := 15260) (by decide) (by decide) (by decide)
    Nice.Cert.Base17_2_3.upto_2 n

end Nice.Cert
