import NiceCertified.TwoThree.Base11.Part000

/-!
Generated by `gen/gen.py 11 2 3 20 --chunked 2500`; do not edit by hand.

The crude band `(74, 196)` in 1 parts, about 2 tree nodes and scanned
candidates in all, checked by the kernel's own tree search with scan width 20.
-/

namespace Nice.Cert

/-- **No `(2,3)`-nice number exists in base 11.** -/
theorem base_11_empty_2_3 (n : Nat) : ¬ Pandigital 11 2 3 n :=
  no_nice_of_free (lo := 74) (hi := 196) (by decide) (by decide) (by decide)
    Nice.Cert.Base11_2_3.upto_0 n

end Nice.Cert
