import NiceCertified.Checker

/-!
Generated by `gen/gen.py 13 2 3 13`; do not edit by hand.

19 intervals covering `(282, 788)`: 2 with the wrong digit lengths,
0 retired by a top-digit clash, 17 scanned candidate by candidate
(212 candidates).
-/

namespace Nice.Cert

def cert_13_2_3 : List Ent := [
  ⟨283, 398, 0, 5, 7, 0⟩,
  ⟨398, 403, 2, 5, 8, 0⟩,
  ⟨403, 416, 2, 5, 8, 0⟩,
  ⟨416, 429, 2, 5, 8, 0⟩,
  ⟨429, 442, 2, 5, 8, 0⟩,
  ⟨442, 455, 2, 5, 8, 0⟩,
  ⟨455, 468, 2, 5, 8, 0⟩,
  ⟨468, 481, 2, 5, 8, 0⟩,
  ⟨481, 494, 2, 5, 8, 0⟩,
  ⟨494, 507, 2, 5, 8, 0⟩,
  ⟨507, 520, 2, 5, 8, 0⟩,
  ⟨520, 533, 2, 5, 8, 0⟩,
  ⟨533, 546, 2, 5, 8, 0⟩,
  ⟨546, 559, 2, 5, 8, 0⟩,
  ⟨559, 572, 2, 5, 8, 0⟩,
  ⟨572, 585, 2, 5, 8, 0⟩,
  ⟨585, 598, 2, 5, 8, 0⟩,
  ⟨598, 610, 2, 5, 8, 0⟩,
  ⟨610, 788, 0, 6, 8, 0⟩]

set_option maxRecDepth 100000 in
theorem cert_13_2_3_ok : checkChain 13 2 3 (282 + 1) cert_13_2_3 788 = true := by
  decide +kernel

/-- **No `(2,3)`-nice number exists in base 13.** -/
theorem base_13_empty_2_3 (n : Nat) : ¬ Pandigital 13 2 3 n :=
  no_nice_of_cert (lo := 282) (hi := 788) (by decide) (by decide) (by decide)
    cert_13_2_3 cert_13_2_3_ok n

end Nice.Cert
