import NiceCertified.TwoThree.Base18

/-!
Generated by `gen/gen.py 19 2 3 20 --chunked 2500`; do not edit by hand.

Part 0 of 7: `[22273, 32851)`, about 2299 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base19_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_0 : NiceFree 19 2 3 22273 32851 :=
  NiceFree.of_chain (by decide) [
    ⟨22273, 29898, 0, 7, 11, 0⟩,
    ⟨29898, 29963, 3, 8, 11, 20⟩,
    ⟨29963, 30324, 3, 8, 11, 20⟩,
    ⟨30324, 30685, 3, 8, 11, 20⟩,
    ⟨30685, 31046, 3, 8, 11, 20⟩,
    ⟨31046, 31407, 3, 8, 11, 20⟩,
    ⟨31407, 31768, 3, 8, 11, 20⟩,
    ⟨31768, 32129, 3, 8, 11, 20⟩,
    ⟨32129, 32490, 3, 8, 11, 20⟩,
    ⟨32490, 32851, 3, 8, 11, 20⟩] (by decide +kernel)

theorem upto_0 : NiceFree 19 2 3 (22272 + 1) 32851 := part_0

end Nice.Cert.Base19_2_3
