import NiceCertified.TwoThree.Base19.Part005

/-!
Generated by `gen/gen.py 19 2 3 20 --chunked 2500`; do not edit by hand.

Part 6 of 7: `[46208, 72321)`, about 2483 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base19_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_6 : NiceFree 19 2 3 46208 72321 :=
  NiceFree.of_chain (by decide) [
    ⟨46208, 46569, 3, 8, 11, 20⟩,
    ⟨46569, 46930, 3, 8, 11, 20⟩,
    ⟨46930, 47291, 3, 8, 11, 20⟩,
    ⟨47291, 47652, 3, 8, 11, 20⟩,
    ⟨47652, 48013, 3, 8, 11, 20⟩,
    ⟨48013, 48839, 3, 8, 11, 20⟩,
    ⟨48839, 72321, 0, 8, 12, 0⟩] (by decide +kernel)

theorem upto_6 : NiceFree 19 2 3 (22272 + 1) 72321 :=
  upto_5.trans part_6

end Nice.Cert.Base19_2_3
