import NiceCertified.TwoThree.Base19.Part001

/-!
Generated by `gen/gen.py 19 2 3 20 --chunked 2500`; do not edit by hand.

Part 2 of 7: `[36100, 38627)`, about 2443 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base19_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_2 : NiceFree 19 2 3 36100 38627 :=
  NiceFree.of_chain (by decide) [
    ⟨36100, 36461, 3, 8, 11, 20⟩,
    ⟨36461, 36822, 3, 8, 11, 20⟩,
    ⟨36822, 37183, 3, 8, 11, 20⟩,
    ⟨37183, 37544, 3, 8, 11, 20⟩,
    ⟨37544, 37905, 3, 8, 11, 20⟩,
    ⟨37905, 38266, 3, 8, 11, 20⟩,
    ⟨38266, 38627, 3, 8, 11, 20⟩] (by decide +kernel)

theorem upto_2 : NiceFree 19 2 3 (22272 + 1) 38627 :=
  upto_1.trans part_2

end Nice.Cert.Base19_2_3
