import NiceCertified.TwoThree.Base19.Part003

/-!
Generated by `gen/gen.py 19 2 3 20 --chunked 2500`; do not edit by hand.

Part 4 of 7: `[41154, 43681)`, about 2291 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base19_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_4 : NiceFree 19 2 3 41154 43681 :=
  NiceFree.of_chain (by decide) [
    ⟨41154, 41515, 3, 8, 11, 20⟩,
    ⟨41515, 41876, 3, 8, 11, 20⟩,
    ⟨41876, 42237, 3, 8, 11, 20⟩,
    ⟨42237, 42598, 3, 8, 11, 20⟩,
    ⟨42598, 42959, 3, 8, 11, 20⟩,
    ⟨42959, 43320, 3, 8, 11, 20⟩,
    ⟨43320, 43681, 3, 8, 11, 20⟩] (by decide +kernel)

theorem upto_4 : NiceFree 19 2 3 (22272 + 1) 43681 :=
  upto_3.trans part_4

end Nice.Cert.Base19_2_3
