import NiceCertified.TwoThree.Base19.Part002

/-!
Generated by `gen/gen.py 19 2 3 20 --chunked 2500`; do not edit by hand.

Part 3 of 7: `[38627, 41154)`, about 2386 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base19_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_3 : NiceFree 19 2 3 38627 41154 :=
  NiceFree.of_chain (by decide) [
    ⟨38627, 38988, 3, 8, 11, 20⟩,
    ⟨38988, 39349, 3, 8, 11, 20⟩,
    ⟨39349, 39710, 3, 8, 11, 20⟩,
    ⟨39710, 40071, 3, 8, 11, 20⟩,
    ⟨40071, 40432, 3, 8, 11, 20⟩,
    ⟨40432, 40793, 3, 8, 11, 20⟩,
    ⟨40793, 41154, 3, 8, 11, 20⟩] (by decide +kernel)

theorem upto_3 : NiceFree 19 2 3 (22272 + 1) 41154 :=
  upto_2.trans part_3

end Nice.Cert.Base19_2_3
