import NiceCertified.TwoThree.Base19.Part000

/-!
Generated by `gen/gen.py 19 2 3 20 --chunked 2500`; do not edit by hand.

Part 1 of 7: `[32851, 36100)`, about 2134 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base19_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_1 : NiceFree 19 2 3 32851 36100 :=
  NiceFree.of_chain (by decide) [
    ⟨32851, 33212, 3, 8, 11, 20⟩,
    ⟨33212, 33573, 3, 8, 11, 20⟩,
    ⟨33573, 33934, 3, 8, 11, 20⟩,
    ⟨33934, 34295, 3, 8, 11, 20⟩,
    ⟨34295, 34656, 3, 8, 11, 20⟩,
    ⟨34656, 35017, 3, 8, 11, 20⟩,
    ⟨35017, 35378, 3, 8, 11, 20⟩,
    ⟨35378, 35739, 3, 8, 11, 20⟩,
    ⟨35739, 36100, 3, 8, 11, 20⟩] (by decide +kernel)

theorem upto_1 : NiceFree 19 2 3 (22272 + 1) 36100 :=
  upto_0.trans part_1

end Nice.Cert.Base19_2_3
