import NiceCertified.TwoThree.Base19.Part004

/-!
Generated by `gen/gen.py 19 2 3 20 --chunked 2500`; do not edit by hand.

Part 5 of 7: `[43681, 46208)`, about 2310 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base19_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_5 : NiceFree 19 2 3 43681 46208 :=
  NiceFree.of_chain (by decide) [
    ⟨43681, 44042, 3, 8, 11, 20⟩,
    ⟨44042, 44403, 3, 8, 11, 20⟩,
    ⟨44403, 44764, 3, 8, 11, 20⟩,
    ⟨44764, 45125, 3, 8, 11, 20⟩,
    ⟨45125, 45486, 3, 8, 11, 20⟩,
    ⟨45486, 45847, 3, 8, 11, 20⟩,
    ⟨45847, 46208, 3, 8, 11, 20⟩] (by decide +kernel)

theorem upto_5 : NiceFree 19 2 3 (22272 + 1) 46208 :=
  upto_4.trans part_5

end Nice.Cert.Base19_2_3
