import NiceCertified.TwoThree.Base13

/-!
Generated by `gen/gen.py 14 2 3 20 --chunked 2500`; do not edit by hand.

Part 0 of 1: `[564, 1619)`, about 444 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base14_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_0 : NiceFree 14 2 3 564 1619 :=
  NiceFree.of_chain (by decide) [
    ⟨564, 734, 0, 5, 8, 0⟩,
    ⟨734, 1139, 3, 6, 8, 20⟩,
    ⟨1139, 1619, 0, 6, 9, 0⟩] (by decide +kernel)

theorem upto_0 : NiceFree 14 2 3 (563 + 1) 1619 := part_0

end Nice.Cert.Base14_2_3
