import NiceCertified.Checker

/-!
Generated by `gen/gen.py 2 2 3 20 --chunked 2500`; do not edit by hand.

Part 0 of 1: `[1, 2)`, about 1 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base2_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_0 : NiceFree 2 2 3 1 2 :=
  NiceFree.of_chain (by decide) [
    ⟨1, 2, 3, 1, 1, 20⟩] (by decide +kernel)

theorem upto_0 : NiceFree 2 2 3 (0 + 1) 2 := part_0

end Nice.Cert.Base2_2_3
