import NiceCertified.TwoThree.Base20.Part026

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 27 of 36: `[132800, 135200)`, about 2142 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_27 : NiceFree 20 2 3 132800 135200 :=
  NiceFree.of_chain (by decide) [
    ⟨132800, 133200, 3, 8, 12, 20⟩,
    ⟨133200, 133600, 3, 8, 12, 20⟩,
    ⟨133600, 134000, 3, 8, 12, 20⟩,
    ⟨134000, 134400, 3, 8, 12, 20⟩,
    ⟨134400, 134800, 3, 8, 12, 20⟩,
    ⟨134800, 135200, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_27 : NiceFree 20 2 3 (48273 + 1) 135200 :=
  upto_26.trans part_27

end Nice.Cert.Base20_2_3
