import NiceCertified.TwoThree.Base20.Part012

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 13 of 36: `[96400, 98800)`, about 2082 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_13 : NiceFree 20 2 3 96400 98800 :=
  NiceFree.of_chain (by decide) [
    ⟨96400, 96800, 3, 8, 12, 20⟩,
    ⟨96800, 97200, 3, 8, 12, 20⟩,
    ⟨97200, 97600, 3, 8, 12, 20⟩,
    ⟨97600, 98000, 3, 8, 12, 20⟩,
    ⟨98000, 98400, 3, 8, 12, 20⟩,
    ⟨98400, 98800, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_13 : NiceFree 20 2 3 (48273 + 1) 98800 :=
  upto_12.trans part_13

end Nice.Cert.Base20_2_3
