import NiceCertified.TwoThree.Base20.Part014

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 15 of 36: `[100800, 104000)`, about 2296 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_15 : NiceFree 20 2 3 100800 104000 :=
  NiceFree.of_chain (by decide) [
    ⟨100800, 101200, 3, 8, 12, 20⟩,
    ⟨101200, 101600, 3, 8, 12, 20⟩,
    ⟨101600, 102000, 3, 8, 12, 20⟩,
    ⟨102000, 102400, 3, 8, 12, 20⟩,
    ⟨102400, 102800, 3, 8, 12, 20⟩,
    ⟨102800, 103200, 3, 8, 12, 20⟩,
    ⟨103200, 103600, 3, 8, 12, 20⟩,
    ⟨103600, 104000, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_15 : NiceFree 20 2 3 (48273 + 1) 104000 :=
  upto_14.trans part_15

end Nice.Cert.Base20_2_3
