import NiceCertified.TwoThree.Base20.Part002

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 3 of 36: `[70400, 72800)`, about 2122 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_3 : NiceFree 20 2 3 70400 72800 :=
  NiceFree.of_chain (by decide) [
    ⟨70400, 70800, 3, 8, 12, 20⟩,
    ⟨70800, 71200, 3, 8, 12, 20⟩,
    ⟨71200, 71600, 3, 8, 12, 20⟩,
    ⟨71600, 72000, 3, 8, 12, 20⟩,
    ⟨72000, 72400, 3, 8, 12, 20⟩,
    ⟨72400, 72800, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_3 : NiceFree 20 2 3 (48273 + 1) 72800 :=
  upto_2.trans part_3

end Nice.Cert.Base20_2_3
