import NiceCertified.TwoThree.Base20.Part015

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 16 of 36: `[104000, 106800)`, about 2469 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_16 : NiceFree 20 2 3 104000 106800 :=
  NiceFree.of_chain (by decide) [
    ⟨104000, 104400, 3, 8, 12, 20⟩,
    ⟨104400, 104800, 3, 8, 12, 20⟩,
    ⟨104800, 105200, 3, 8, 12, 20⟩,
    ⟨105200, 105600, 3, 8, 12, 20⟩,
    ⟨105600, 106000, 3, 8, 12, 20⟩,
    ⟨106000, 106400, 3, 8, 12, 20⟩,
    ⟨106400, 106800, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_16 : NiceFree 20 2 3 (48273 + 1) 106800 :=
  upto_15.trans part_16

end Nice.Cert.Base20_2_3
