import NiceCertified.TwoThree.Base20.Part017

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 18 of 36: `[110000, 112400)`, about 2322 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_18 : NiceFree 20 2 3 110000 112400 :=
  NiceFree.of_chain (by decide) [
    ⟨110000, 110400, 3, 8, 12, 20⟩,
    ⟨110400, 110800, 3, 8, 12, 20⟩,
    ⟨110800, 111200, 3, 8, 12, 20⟩,
    ⟨111200, 111600, 3, 8, 12, 20⟩,
    ⟨111600, 112000, 3, 8, 12, 20⟩,
    ⟨112000, 112400, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_18 : NiceFree 20 2 3 (48273 + 1) 112400 :=
  upto_17.trans part_18

end Nice.Cert.Base20_2_3
