import NiceCertified.TwoThree.Base20.Part006

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 7 of 36: `[81200, 83600)`, about 2202 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_7 : NiceFree 20 2 3 81200 83600 :=
  NiceFree.of_chain (by decide) [
    ⟨81200, 81600, 3, 8, 12, 20⟩,
    ⟨81600, 82000, 3, 8, 12, 20⟩,
    ⟨82000, 82400, 3, 8, 12, 20⟩,
    ⟨82400, 82800, 3, 8, 12, 20⟩,
    ⟨82800, 83200, 3, 8, 12, 20⟩,
    ⟨83200, 83600, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_7 : NiceFree 20 2 3 (48273 + 1) 83600 :=
  upto_6.trans part_7

end Nice.Cert.Base20_2_3
