import NiceCertified.TwoThree.Base20.Part009

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 10 of 36: `[89200, 91600)`, about 2222 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_10 : NiceFree 20 2 3 89200 91600 :=
  NiceFree.of_chain (by decide) [
    ⟨89200, 89600, 3, 8, 12, 20⟩,
    ⟨89600, 90000, 3, 8, 12, 20⟩,
    ⟨90000, 90400, 3, 8, 12, 20⟩,
    ⟨90400, 90800, 3, 8, 12, 20⟩,
    ⟨90800, 91200, 3, 8, 12, 20⟩,
    ⟨91200, 91600, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_10 : NiceFree 20 2 3 (48273 + 1) 91600 :=
  upto_9.trans part_10

end Nice.Cert.Base20_2_3
