import NiceCertified.TwoThree.Base20.Part025

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 26 of 36: `[130400, 132800)`, about 2142 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_26 : NiceFree 20 2 3 130400 132800 :=
  NiceFree.of_chain (by decide) [
    ⟨130400, 130800, 3, 8, 12, 20⟩,
    ⟨130800, 131200, 3, 8, 12, 20⟩,
    ⟨131200, 131600, 3, 8, 12, 20⟩,
    ⟨131600, 132000, 3, 8, 12, 20⟩,
    ⟨132000, 132400, 3, 8, 12, 20⟩,
    ⟨132400, 132800, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_26 : NiceFree 20 2 3 (48273 + 1) 132800 :=
  upto_25.trans part_26

end Nice.Cert.Base20_2_3
