import NiceCertified.TwoThree.Base20.Part013

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 14 of 36: `[98800, 100800)`, about 2135 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_14 : NiceFree 20 2 3 98800 100800 :=
  NiceFree.of_chain (by decide) [
    ⟨98800, 99200, 3, 8, 12, 20⟩,
    ⟨99200, 99600, 3, 8, 12, 20⟩,
    ⟨99600, 100000, 3, 8, 12, 20⟩,
    ⟨100000, 100400, 3, 8, 12, 20⟩,
    ⟨100400, 100800, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_14 : NiceFree 20 2 3 (48273 + 1) 100800 :=
  upto_13.trans part_14

end Nice.Cert.Base20_2_3
