import NiceCertified.TwoThree.Base20.Part008

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 9 of 36: `[85600, 89200)`, about 2383 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_9 : NiceFree 20 2 3 85600 89200 :=
  NiceFree.of_chain (by decide) [
    ⟨85600, 86000, 3, 8, 12, 20⟩,
    ⟨86000, 86400, 3, 8, 12, 20⟩,
    ⟨86400, 86800, 3, 8, 12, 20⟩,
    ⟨86800, 87200, 3, 8, 12, 20⟩,
    ⟨87200, 87600, 3, 8, 12, 20⟩,
    ⟨87600, 88000, 3, 8, 12, 20⟩,
    ⟨88000, 88400, 3, 8, 12, 20⟩,
    ⟨88400, 88800, 3, 8, 12, 20⟩,
    ⟨88800, 89200, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_9 : NiceFree 20 2 3 (48273 + 1) 89200 :=
  upto_8.trans part_9

end Nice.Cert.Base20_2_3
