import NiceCertified.TwoThree.Base20.Part004

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 5 of 36: `[76000, 78800)`, about 2409 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_5 : NiceFree 20 2 3 76000 78800 :=
  NiceFree.of_chain (by decide) [
    ⟨76000, 76400, 3, 8, 12, 20⟩,
    ⟨76400, 76800, 3, 8, 12, 20⟩,
    ⟨76800, 77200, 3, 8, 12, 20⟩,
    ⟨77200, 77600, 3, 8, 12, 20⟩,
    ⟨77600, 78000, 3, 8, 12, 20⟩,
    ⟨78000, 78400, 3, 8, 12, 20⟩,
    ⟨78400, 78800, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_5 : NiceFree 20 2 3 (48273 + 1) 78800 :=
  upto_4.trans part_5

end Nice.Cert.Base20_2_3
