import NiceCertified.TwoThree.Base20.Part029

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 30 of 36: `[140800, 143600)`, about 2329 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_30 : NiceFree 20 2 3 140800 143600 :=
  NiceFree.of_chain (by decide) [
    ⟨140800, 141200, 3, 8, 12, 20⟩,
    ⟨141200, 141600, 3, 8, 12, 20⟩,
    ⟨141600, 142000, 3, 8, 12, 20⟩,
    ⟨142000, 142400, 3, 8, 12, 20⟩,
    ⟨142400, 142800, 3, 8, 12, 20⟩,
    ⟨142800, 143200, 3, 8, 12, 20⟩,
    ⟨143200, 143600, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_30 : NiceFree 20 2 3 (48273 + 1) 143600 :=
  upto_29.trans part_30

end Nice.Cert.Base20_2_3
