import NiceCertified.TwoThree.Base20.Part031

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 32 of 36: `[146000, 148800)`, about 2369 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_32 : NiceFree 20 2 3 146000 148800 :=
  NiceFree.of_chain (by decide) [
    ⟨146000, 146400, 3, 8, 12, 20⟩,
    ⟨146400, 146800, 3, 8, 12, 20⟩,
    ⟨146800, 147200, 3, 8, 12, 20⟩,
    ⟨147200, 147600, 3, 8, 12, 20⟩,
    ⟨147600, 148000, 3, 8, 12, 20⟩,
    ⟨148000, 148400, 3, 8, 12, 20⟩,
    ⟨148400, 148800, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_32 : NiceFree 20 2 3 (48273 + 1) 148800 :=
  upto_31.trans part_32

end Nice.Cert.Base20_2_3
