import NiceCertified.TwoThree.Base20.Part022

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 23 of 36: `[122800, 125200)`, about 2362 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_23 : NiceFree 20 2 3 122800 125200 :=
  NiceFree.of_chain (by decide) [
    ⟨122800, 123200, 3, 8, 12, 20⟩,
    ⟨123200, 123600, 3, 8, 12, 20⟩,
    ⟨123600, 124000, 3, 8, 12, 20⟩,
    ⟨124000, 124400, 3, 8, 12, 20⟩,
    ⟨124400, 124800, 3, 8, 12, 20⟩,
    ⟨124800, 125200, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_23 : NiceFree 20 2 3 (48273 + 1) 125200 :=
  upto_22.trans part_23

end Nice.Cert.Base20_2_3
