import NiceCertified.TwoThree.Base20.Part000

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 1 of 36: `[64400, 68000)`, about 2497 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_1 : NiceFree 20 2 3 64400 68000 :=
  NiceFree.of_chain (by decide) [
    ⟨64400, 64800, 3, 8, 12, 20⟩,
    ⟨64800, 65200, 3, 8, 12, 20⟩,
    ⟨65200, 65600, 3, 8, 12, 20⟩,
    ⟨65600, 66000, 3, 8, 12, 20⟩,
    ⟨66000, 66400, 3, 8, 12, 20⟩,
    ⟨66400, 66800, 3, 8, 12, 20⟩,
    ⟨66800, 67200, 3, 8, 12, 20⟩,
    ⟨67200, 67600, 3, 8, 12, 20⟩,
    ⟨67600, 68000, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_1 : NiceFree 20 2 3 (48273 + 1) 68000 :=
  upto_0.trans part_1

end Nice.Cert.Base20_2_3
