import NiceCertified.TwoThree.Base20.Part028

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 29 of 36: `[138000, 140800)`, about 2369 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_29 : NiceFree 20 2 3 138000 140800 :=
  NiceFree.of_chain (by decide) [
    ⟨138000, 138400, 3, 8, 12, 20⟩,
    ⟨138400, 138800, 3, 8, 12, 20⟩,
    ⟨138800, 139200, 3, 8, 12, 20⟩,
    ⟨139200, 139600, 3, 8, 12, 20⟩,
    ⟨139600, 140000, 3, 8, 12, 20⟩,
    ⟨140000, 140400, 3, 8, 12, 20⟩,
    ⟨140400, 140800, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_29 : NiceFree 20 2 3 (48273 + 1) 140800 :=
  upto_28.trans part_29

end Nice.Cert.Base20_2_3
