import NiceCertified.TwoThree.Base20.Part027

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 28 of 36: `[135200, 138000)`, about 2469 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_28 : NiceFree 20 2 3 135200 138000 :=
  NiceFree.of_chain (by decide) [
    ⟨135200, 135600, 3, 8, 12, 20⟩,
    ⟨135600, 136000, 3, 8, 12, 20⟩,
    ⟨136000, 136400, 3, 8, 12, 20⟩,
    ⟨136400, 136800, 3, 8, 12, 20⟩,
    ⟨136800, 137200, 3, 8, 12, 20⟩,
    ⟨137200, 137600, 3, 8, 12, 20⟩,
    ⟨137600, 138000, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_28 : NiceFree 20 2 3 (48273 + 1) 138000 :=
  upto_27.trans part_28

end Nice.Cert.Base20_2_3
