import NiceCertified.TwoThree.Base20.Part003

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 4 of 36: `[72800, 76000)`, about 2496 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_4 : NiceFree 20 2 3 72800 76000 :=
  NiceFree.of_chain (by decide) [
    ⟨72800, 73200, 3, 8, 12, 20⟩,
    ⟨73200, 73600, 3, 8, 12, 20⟩,
    ⟨73600, 74000, 3, 8, 12, 20⟩,
    ⟨74000, 74400, 3, 8, 12, 20⟩,
    ⟨74400, 74800, 3, 8, 12, 20⟩,
    ⟨74800, 75200, 3, 8, 12, 20⟩,
    ⟨75200, 75600, 3, 8, 12, 20⟩,
    ⟨75600, 76000, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_4 : NiceFree 20 2 3 (48273 + 1) 76000 :=
  upto_3.trans part_4

end Nice.Cert.Base20_2_3
