import NiceCertified.TwoThree.Base20.Part020

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 21 of 36: `[117600, 120000)`, about 2402 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_21 : NiceFree 20 2 3 117600 120000 :=
  NiceFree.of_chain (by decide) [
    ⟨117600, 118000, 3, 8, 12, 20⟩,
    ⟨118000, 118400, 3, 8, 12, 20⟩,
    ⟨118400, 118800, 3, 8, 12, 20⟩,
    ⟨118800, 119200, 3, 8, 12, 20⟩,
    ⟨119200, 119600, 3, 8, 12, 20⟩,
    ⟨119600, 120000, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_21 : NiceFree 20 2 3 (48273 + 1) 120000 :=
  upto_20.trans part_21

end Nice.Cert.Base20_2_3
