import NiceCertified.TwoThree.Base19

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 0 of 36: `[48274, 64400)`, about 2375 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_0 : NiceFree 20 2 3 48274 64400 :=
  NiceFree.of_chain (by decide) [
    ⟨48274, 58945, 0, 8, 11, 0⟩,
    ⟨58945, 64000, 3, 8, 12, 20⟩,
    ⟨64000, 64400, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_0 : NiceFree 20 2 3 (48273 + 1) 64400 := part_0

end Nice.Cert.Base20_2_3
