import NiceCertified.TwoThree.Base20.Part033

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 34 of 36: `[151600, 154000)`, about 2382 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_34 : NiceFree 20 2 3 151600 154000 :=
  NiceFree.of_chain (by decide) [
    ⟨151600, 152000, 3, 8, 12, 20⟩,
    ⟨152000, 152400, 3, 8, 12, 20⟩,
    ⟨152400, 152800, 3, 8, 12, 20⟩,
    ⟨152800, 153200, 3, 8, 12, 20⟩,
    ⟨153200, 153600, 3, 8, 12, 20⟩,
    ⟨153600, 154000, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_34 : NiceFree 20 2 3 (48273 + 1) 154000 :=
  upto_33.trans part_34

end Nice.Cert.Base20_2_3
