import NiceCertified.TwoThree.Base20.Part018

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 19 of 36: `[112400, 114800)`, about 2382 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_19 : NiceFree 20 2 3 112400 114800 :=
  NiceFree.of_chain (by decide) [
    ⟨112400, 112800, 3, 8, 12, 20⟩,
    ⟨112800, 113200, 3, 8, 12, 20⟩,
    ⟨113200, 113600, 3, 8, 12, 20⟩,
    ⟨113600, 114000, 3, 8, 12, 20⟩,
    ⟨114000, 114400, 3, 8, 12, 20⟩,
    ⟨114400, 114800, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_19 : NiceFree 20 2 3 (48273 + 1) 114800 :=
  upto_18.trans part_19

end Nice.Cert.Base20_2_3
