import NiceCertified.TwoThree.Base20.Part024

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 25 of 36: `[128000, 130400)`, about 2242 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_25 : NiceFree 20 2 3 128000 130400 :=
  NiceFree.of_chain (by decide) [
    ⟨128000, 128400, 3, 8, 12, 20⟩,
    ⟨128400, 128800, 3, 8, 12, 20⟩,
    ⟨128800, 129200, 3, 8, 12, 20⟩,
    ⟨129200, 129600, 3, 8, 12, 20⟩,
    ⟨129600, 130000, 3, 8, 12, 20⟩,
    ⟨130000, 130400, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_25 : NiceFree 20 2 3 (48273 + 1) 130400 :=
  upto_24.trans part_25

end Nice.Cert.Base20_2_3
