import NiceCertified.TwoThree.Base20.Part016

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 17 of 36: `[106800, 110000)`, about 2336 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_17 : NiceFree 20 2 3 106800 110000 :=
  NiceFree.of_chain (by decide) [
    ⟨106800, 107200, 3, 8, 12, 20⟩,
    ⟨107200, 107600, 3, 8, 12, 20⟩,
    ⟨107600, 108000, 3, 8, 12, 20⟩,
    ⟨108000, 108400, 3, 8, 12, 20⟩,
    ⟨108400, 108800, 3, 8, 12, 20⟩,
    ⟨108800, 109200, 3, 8, 12, 20⟩,
    ⟨109200, 109600, 3, 8, 12, 20⟩,
    ⟨109600, 110000, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_17 : NiceFree 20 2 3 (48273 + 1) 110000 :=
  upto_16.trans part_17

end Nice.Cert.Base20_2_3
