import NiceCertified.TwoThree.Base20.Part030

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 31 of 36: `[143600, 146000)`, about 2302 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_31 : NiceFree 20 2 3 143600 146000 :=
  NiceFree.of_chain (by decide) [
    ⟨143600, 144000, 3, 8, 12, 20⟩,
    ⟨144000, 144400, 3, 8, 12, 20⟩,
    ⟨144400, 144800, 3, 8, 12, 20⟩,
    ⟨144800, 145200, 3, 8, 12, 20⟩,
    ⟨145200, 145600, 3, 8, 12, 20⟩,
    ⟨145600, 146000, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_31 : NiceFree 20 2 3 (48273 + 1) 146000 :=
  upto_30.trans part_31

end Nice.Cert.Base20_2_3
