import NiceCertified.TwoThree.Base20.Part019

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 20 of 36: `[114800, 117600)`, about 2229 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_20 : NiceFree 20 2 3 114800 117600 :=
  NiceFree.of_chain (by decide) [
    ⟨114800, 115200, 3, 8, 12, 20⟩,
    ⟨115200, 115600, 3, 8, 12, 20⟩,
    ⟨115600, 116000, 3, 8, 12, 20⟩,
    ⟨116000, 116400, 3, 8, 12, 20⟩,
    ⟨116400, 116800, 3, 8, 12, 20⟩,
    ⟨116800, 117200, 3, 8, 12, 20⟩,
    ⟨117200, 117600, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_20 : NiceFree 20 2 3 (48273 + 1) 117600 :=
  upto_19.trans part_20

end Nice.Cert.Base20_2_3
