import NiceCertified.TwoThree.Base20.Part007

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 8 of 36: `[83600, 85600)`, about 2135 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_8 : NiceFree 20 2 3 83600 85600 :=
  NiceFree.of_chain (by decide) [
    ⟨83600, 84000, 3, 8, 12, 20⟩,
    ⟨84000, 84400, 3, 8, 12, 20⟩,
    ⟨84400, 84800, 3, 8, 12, 20⟩,
    ⟨84800, 85200, 3, 8, 12, 20⟩,
    ⟨85200, 85600, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_8 : NiceFree 20 2 3 (48273 + 1) 85600 :=
  upto_7.trans part_8

end Nice.Cert.Base20_2_3
