import NiceCertified.TwoThree.Base20.Part034

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 35 of 36: `[154000, 160000)`, about 1617 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_35 : NiceFree 20 2 3 154000 160000 :=
  NiceFree.of_chain (by decide) [
    ⟨154000, 154400, 3, 8, 12, 20⟩,
    ⟨154400, 154800, 3, 8, 12, 20⟩,
    ⟨154800, 155200, 3, 8, 12, 20⟩,
    ⟨155200, 155600, 3, 8, 12, 20⟩,
    ⟨155600, 156000, 3, 8, 12, 20⟩,
    ⟨156000, 156400, 3, 8, 12, 20⟩,
    ⟨156400, 156800, 3, 8, 12, 20⟩,
    ⟨156800, 157200, 3, 8, 12, 20⟩,
    ⟨157200, 157600, 3, 8, 12, 20⟩,
    ⟨157600, 158000, 3, 8, 12, 20⟩,
    ⟨158000, 158400, 3, 8, 12, 20⟩,
    ⟨158400, 158800, 3, 8, 12, 20⟩,
    ⟨158800, 159200, 3, 8, 12, 20⟩,
    ⟨159200, 159600, 3, 8, 12, 20⟩,
    ⟨159600, 160000, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_35 : NiceFree 20 2 3 (48273 + 1) 160000 :=
  upto_34.trans part_35

end Nice.Cert.Base20_2_3
