import NiceCertified.TwoThree.Base20.Part005

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 6 of 36: `[78800, 81200)`, about 2102 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_6 : NiceFree 20 2 3 78800 81200 :=
  NiceFree.of_chain (by decide) [
    ⟨78800, 79200, 3, 8, 12, 20⟩,
    ⟨79200, 79600, 3, 8, 12, 20⟩,
    ⟨79600, 80000, 3, 8, 12, 20⟩,
    ⟨80000, 80400, 3, 8, 12, 20⟩,
    ⟨80400, 80800, 3, 8, 12, 20⟩,
    ⟨80800, 81200, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_6 : NiceFree 20 2 3 (48273 + 1) 81200 :=
  upto_5.trans part_6

end Nice.Cert.Base20_2_3
