import NiceCertified.TwoThree.Base20.Part023

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 24 of 36: `[125200, 128000)`, about 2369 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_24 : NiceFree 20 2 3 125200 128000 :=
  NiceFree.of_chain (by decide) [
    ⟨125200, 125600, 3, 8, 12, 20⟩,
    ⟨125600, 126000, 3, 8, 12, 20⟩,
    ⟨126000, 126400, 3, 8, 12, 20⟩,
    ⟨126400, 126800, 3, 8, 12, 20⟩,
    ⟨126800, 127200, 3, 8, 12, 20⟩,
    ⟨127200, 127600, 3, 8, 12, 20⟩,
    ⟨127600, 128000, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_24 : NiceFree 20 2 3 (48273 + 1) 128000 :=
  upto_23.trans part_24

end Nice.Cert.Base20_2_3
