import NiceCertified.TwoThree.Base20.Part010

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 11 of 36: `[91600, 93600)`, about 2135 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_11 : NiceFree 20 2 3 91600 93600 :=
  NiceFree.of_chain (by decide) [
    ⟨91600, 92000, 3, 8, 12, 20⟩,
    ⟨92000, 92400, 3, 8, 12, 20⟩,
    ⟨92400, 92800, 3, 8, 12, 20⟩,
    ⟨92800, 93200, 3, 8, 12, 20⟩,
    ⟨93200, 93600, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_11 : NiceFree 20 2 3 (48273 + 1) 93600 :=
  upto_10.trans part_11

end Nice.Cert.Base20_2_3
