import NiceCertified.TwoThree.Base20.Part011

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 12 of 36: `[93600, 96400)`, about 2309 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_12 : NiceFree 20 2 3 93600 96400 :=
  NiceFree.of_chain (by decide) [
    ⟨93600, 94000, 3, 8, 12, 20⟩,
    ⟨94000, 94400, 3, 8, 12, 20⟩,
    ⟨94400, 94800, 3, 8, 12, 20⟩,
    ⟨94800, 95200, 3, 8, 12, 20⟩,
    ⟨95200, 95600, 3, 8, 12, 20⟩,
    ⟨95600, 96000, 3, 8, 12, 20⟩,
    ⟨96000, 96400, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_12 : NiceFree 20 2 3 (48273 + 1) 96400 :=
  upto_11.trans part_12

end Nice.Cert.Base20_2_3
