import NiceCertified.TwoThree.Base20.Part001

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 2 of 36: `[68000, 70400)`, about 2442 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_2 : NiceFree 20 2 3 68000 70400 :=
  NiceFree.of_chain (by decide) [
    ⟨68000, 68400, 3, 8, 12, 20⟩,
    ⟨68400, 68800, 3, 8, 12, 20⟩,
    ⟨68800, 69200, 3, 8, 12, 20⟩,
    ⟨69200, 69600, 3, 8, 12, 20⟩,
    ⟨69600, 70000, 3, 8, 12, 20⟩,
    ⟨70000, 70400, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_2 : NiceFree 20 2 3 (48273 + 1) 70400 :=
  upto_1.trans part_2

end Nice.Cert.Base20_2_3
