import NiceCertified.TwoThree.Base20.Part032

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 33 of 36: `[148800, 151600)`, about 2469 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_33 : NiceFree 20 2 3 148800 151600 :=
  NiceFree.of_chain (by decide) [
    ⟨148800, 149200, 3, 8, 12, 20⟩,
    ⟨149200, 149600, 3, 8, 12, 20⟩,
    ⟨149600, 150000, 3, 8, 12, 20⟩,
    ⟨150000, 150400, 3, 8, 12, 20⟩,
    ⟨150400, 150800, 3, 8, 12, 20⟩,
    ⟨150800, 151200, 3, 8, 12, 20⟩,
    ⟨151200, 151600, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_33 : NiceFree 20 2 3 (48273 + 1) 151600 :=
  upto_32.trans part_33

end Nice.Cert.Base20_2_3
