import NiceCertified.TwoThree.Base20.Part021

/-!
Generated by `gen/gen.py 20 2 3 20 --chunked 2500`; do not edit by hand.

Part 22 of 36: `[120000, 122800)`, about 2229 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base20_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_22 : NiceFree 20 2 3 120000 122800 :=
  NiceFree.of_chain (by decide) [
    ⟨120000, 120400, 3, 8, 12, 20⟩,
    ⟨120400, 120800, 3, 8, 12, 20⟩,
    ⟨120800, 121200, 3, 8, 12, 20⟩,
    ⟨121200, 121600, 3, 8, 12, 20⟩,
    ⟨121600, 122000, 3, 8, 12, 20⟩,
    ⟨122000, 122400, 3, 8, 12, 20⟩,
    ⟨122400, 122800, 3, 8, 12, 20⟩] (by decide +kernel)

theorem upto_22 : NiceFree 20 2 3 (48273 + 1) 122800 :=
  upto_21.trans part_22

end Nice.Cert.Base20_2_3
