import NiceCertified.TwoThree.Base7

/-!
Generated by `gen/gen.py 8 2 3 20 --chunked 2500`; do not edit by hand.

Part 0 of 1: `[13, 28)`, about 10 tree nodes and scanned
candidates.  Each part is its own module importing the one before, and each base's
first part imports the previous base, so a build checks one part at a time.
-/

namespace Nice.Cert.Base8_2_3

open Nice Nice.Cert

set_option maxRecDepth 100000 in
theorem part_0 : NiceFree 8 2 3 13 28 :=
  NiceFree.of_chain (by decide) [
    ⟨13, 16, 0, 3, 4, 0⟩,
    ⟨16, 23, 3, 3, 5, 20⟩,
    ⟨23, 28, 0, 4, 5, 0⟩] (by decide +kernel)

theorem upto_0 : NiceFree 8 2 3 (12 + 1) 28 := part_0

end Nice.Cert.Base8_2_3
